apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  labels:
    app: celery-beat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: celery-beat
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              value: "dev"
            - name: SENTRY_RELEASE
              value: "82d1bcd221199cd9ad9beb930239a58b38340cba-dev"
            - name: OTEL_ENABLED
              value: "1"
