apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    spec:
      containers:
        - name: celery-worker
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              value: "dev"
            - name: SENTRY_RELEASE
              value: "82d1bcd221199cd9ad9beb930239a58b38340cba-dev"
            - name: OTEL_ENABLED
              value: "1"
