# Generated by Django 3.2.9 on 2024-05-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [

    ]
