# Generated by Django 3.2.9 on 2024-05-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscore',
            old_name='high_score',
            new_name='High_score',
        ),
        migrations.RenameField(
            model_name='userscore',
            old_name='easy_score',
            new_name='Low_score',
        ),
        migrations.RenameField(
            model_name='userscore',
            old_name='medium_score',
            new_name='Mid_score',
        ),
        migrations.RenameField(
            model_name='userscore',
            old_name='very_high_score',
            new_name='VeryHigh_score',
        ),
        migrations.RenameField(
            model_name='userscore',
            old_name='very_low_score',
            new_name='VeryLow_score',
        ),
    ]
