# Generated by Django 3.2.9 on 2024-01-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='fluctuation',
            field=models.IntegerField(default=0),
        ),
    ]
