# Generated by Django 3.2.9 on 2024-01-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20240108_0729'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='score',
            table='user_score',
        ),
    ]
