# Generated by Django 3.2.9 on 2024-01-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_score_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='prev_score',
            field=models.IntegerField(default=0),
        ),
    ]
