# Generated by Django 3.2.9 on 2024-01-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_score_prev_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='prev_score',
            new_name='basis',
        ),
    ]
