# Generated by Django 3.2.9 on 2024-02-13 06:21

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_prev_score_score_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='field_score',
            field=models.JSONField(default=account.models.get_default_field_score),
        ),
    ]
