# Generated by Django 3.2.9 on 2024-02-23 04:56

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile_field_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='basis',
            new_name='yesterday_score',
        ),
        migrations.AddField(
            model_name='score',
            name='tier',
            field=models.TextField(default=account.models.get_default_tier),
        ),
    ]
