# Generated by Django 3.2.9 on 2024-02-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20240223_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='total_score',
        ),
        migrations.AddField(
            model_name='score',
            name='datastructure_score',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='implementation_score',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='math_score',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='search_score',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='sorting_score',
            field=models.BigIntegerField(default=0),
        ),
    ]
