# Generated by Django 3.2.9 on 2024-02-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20240223_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='field_score',
        ),
    ]
