# Generated by Django 3.2.9 on 2024-02-23 06:14

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_userprofile_field_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='current_tier_score',
            field=models.IntegerField(default=account.models.get_default_current_tier_score),
        ),
        migrations.AddField(
            model_name='score',
            name='next_tier_score',
            field=models.IntegerField(default=account.models.get_default_next_tier_score),
        ),
    ]
