# Generated by Django 3.2.9 on 2023-12-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20231203_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='college_name',
            new_name='college',
        ),
    ]
