# Generated by Django 3.2.9 on 2024-01-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20231203_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.TextField(null=True),
        ),
    ]
