# Generated by Django 3.2.25 on 2025-09-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='allow_paste',
            field=models.BooleanField(default=True),
        ),
    ]
