# Generated by Django 3.2.25 on 2026-04-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_allow_paste'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='ai_assistant_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
