prometheus:
  prometheusSpec:
    evaluationInterval: 15s
    scrapeInterval: 15s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    alertmanagerConfigMatcherStrategy:
      type: None
    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerConfig: codeplace
    alertmanagerConfigNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: monitoring

grafana:
  additionalDataSources:
    - name: Loki
      uid: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      isDefault: false
      jsonData:
        timeout: 60
    - name: Tempo
      uid: Tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3200
      isDefault: false
      jsonData:
        tracesToLogsV2:
          datasourceUid: Loki
          spanStartTimeShift: "-5m"
          spanEndTimeShift: "5m"
          filterByTraceID: false
          filterBySpanID: false
          customQuery: true
          query: "{namespace=~\"code-place-dev|code-place-prod\"} |= \"${__span.traceId}\""
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.tls.certresolver: default
    hosts:
      - monitoring.code-place-dev.site
    tls:
      - hosts:
          - monitoring.code-place-dev.site
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
