apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  jobLabel: app.kubernetes.io/name
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
