apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - code-place-prod
  selector:
    matchLabels:
      app: vllm
  jobLabel: app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
