---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDA0TI6cEMA7hp9HOn35I8/2T6uYkVZrjyIWv1zRh/1rSi8ZRJg2g2iC38MpvjYQSSlIaNUWJQi+FivJtW11MRgQ+skZ82OO39lU70LK+1+VL1X5qFfEWq28gh1YszljPGUfuFL/jPxvm4YJs04n0aEUmb0ULu6EqzZwPdr6emv4YOH1frsETaipGV2z8XkPmHr7ON5yxzqTS+racI7kj7ImJ0L1P9fIdl6KrmF93memd1uevvMU1oefLSp2jbmc6Ms0GH9nHbX4DePtB4WJBG9Vv8Q7PfJZ02ktkwE61Lho7+qexDXIgzy0GuNBrfv65sbRf1q0qTOO5tcgnk01zMbzKInaT+j6/hpnvC5VyBoF8Tsf+63AQ0+DDDHO381G0S94Oe9v04norscE4cFN+qdUeAJEcTbrDY+c++qe3yw+2s8PlrEZBslsSisVeLVLmP16/9Y2atA1ZHUvB5sOTGLivlqRRifoRFv/gdeL2jIEmn4maWRp4Iec2IWMJ+OFl5Tg/FQ+Ft7zfC0k4T6M00fsHSrcg+Tmn3kF4hV/vMPWLWD5PHjI71kDVOSseQOXj126zXm1TuyoTlPJetuSHXJ8hw0/4wVZrv2bAixgzHHkbwk0+PQe10fgTk3F2OSxUwmCCIMb5fiyee09/1y4cwzDNTsytr/hIpSdSbTzZv4H/Mstu1rRudCpDzQM7VfrFo1FpMf77PdmuF6
    admin-user: AgCFcX74+X//E2Z1tvjUQuQTJs2bW7YdUcl2zTppHCeJhVUfkmjvCG7q9LJdJyOvCsHF+REvDgdC0ba5FnmKExCyR8gDPCLaY1Fcoc3TwYcl7/fW434+ruz49+qPXaIBDZNVrmzyJrrQRr17E2Dp0bHZXnRstOlCXzldo/A3VEUa5W09ESgrViY6pPCYVAojCyQwmUtsVRhV/kfZzciQalHOhDWKRgGg+WEwjLwuTf0Eo86EJXJONVVeNY9tEjlU5DhQPdk+XekxC0Yphte7Yfc3Vd+6IculZ75X7HOin0AmPpEsBCxb1Aduu7zKz+ecmkmALrFHrq2Pu0427NPixMC5cKxTs/pzyAOoOo7/TJUWH9isDglgX6T3IvAesznI01nckWvMcQWPzRyLZMqSg62mBm2+jrQWusTrPv6mXT5BhTspOa2SXsO9tVL1Av5b2qLf4UjdQ75wWg2LBDIf5dZffBbErup4nQmko+X+wzy61tp15FEXDzlSyA4c+RmLIYQUMzKV3LKNpLZhXOnUKCDV7C/RjOhqNbSiYvMfW30Aq9enyGYwyzejQhJu0GGrtzCFWNr/I8/D5YFKzVHxc78oi3YdkjEX8P7WSh9c9UgkirI/VG5yW6chVY5BbdKzS986P0RFK8R7MWAdYQKDsq9cu/9xGKN4+xlsmqStJn0OFcdZYkCq9V2xTJ7WL0hhnkyfsXIv7g==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
