# Generated by Django 3.2.25 on 2024-07-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.TextField()),
                ('link_url', models.URLField()),
                ('visible', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banner',
                'ordering': ('order', '-create_time'),
            },
        ),
    ]
