# Generated by Django 3.2.9 on 2024-12-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.TextField(),
        ),
    ]
