# Generated by Django 3.2.25 on 2024-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_banner_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
