prometheus:
  prometheusSpec:
    evaluationInterval: 15s
    scrapeInterval: 15s
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerConfig: codeplace
    alertmanagerConfigNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: monitoring

grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
