---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: code-place-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAw50uDuJxBhjD9MQAbm6eYk5hK6Rvq6f6RoVhTueMMhSvDsg5l9nrjJ6WYVbY7zMloPbo5VJKTlPrQAc4Os3af8fqtZBfeNIQuP6dVHmWKtsKho1JleKoGsN/dQnbmrVACYrT1Ip4xmiTGPDA4U68YUvLxJR8zfdid6XL/MgoC8mCaVO2heshUX99LdA/7FSHvV3vQ5zPNGtLaYM0qEhptMehk3ttJnkbLAJJUbytKu1YWc7jQNn1hq8zP/hjrxWD2NhnS0rzcDd4Vim6E2M4VlR3BF7p7R8Fzj4hy07HSPGwauRleKkV8ngqmit9V9v1QI4DZNY67Gf3VmlqHhNkDYLCfldXkrrnF2MpHvJpEloay954KcOLjJIgn3iEcUZJXKwH6zXIy3dJv+vMm1zmQlJ/nLvqPgHOluMmO/tCyIJOC9+Uqb5xvNLHrVPMT9v0Qi3h6GSWJTNykMH0UT6CDoui+QxZzoJxvI6oH65GKwMgda2DrOIyHStJJF9/9K2uMvlUZiSNdq5fNoLeaGq0Ra2p/SXtlgHBGrgibMjXYl4jtMk6Z/2GIehGuWvczT4zoey72rUN2/N/vCWw+qxYGTrllWEvs2VeU5cRgw8FYwK3hwiHg5ZIAGRrm6MdCNmVDaFVh6dGn0Ay5eJjqj3GuD9fn8FEZ/vhQSc38ya8Qj92AyH+JRkk312HtIxw34f2EiYhlUL2MslX7+wOu2PZdZr/5KMThiwqKjqU2JoXcdvQ/VV+xPFVfbeaXfu4kMWste08yfbWRrvCLjmVbXr7iBmqd/7laEsTvBA/1orzWf75k8uML/DzT0Hb9PrJ2nvsBPU7mMMfgieBHxHXKeN+fdIkfrqJeul4KiWS6dw==
  template:
    metadata:
      name: regcred
      namespace: code-place-dev
    type: kubernetes.io/dockerconfigjson
