---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentry-secret
  namespace: code-place-dev
spec:
  encryptedData:
    SENTRY_DSN_BACKEND: AgAySA68Zyangz6cxq0z1CoOLXL+t7CMfgTJIOCdcRpfCxVsJw10IEIpCFJKsLEQQoUwbWEmTP1AbeR17/BuDj8zRIMGgljI6CfsnsLDemiKXgcGdQddjZ8UDJnMcG+VFSD3xI8C3dCoPGRp/CN82U6XQE4CTTh/iBsXn/5yoQjTeml/TlXpVO8RcECRlQrDXWfnVyMXQUbOEUlEghj4I/VECEgO2PA01i1HM4x3MPubCktGILzqC+HS6CNVXQk5L+FKipwWAxreSs3r8vzesCk9Dd80caTNayfMAbpwocp6/gfh5PPM+4i7cdYvwfzecdJqbKHFEOeisgmC+ICz5a4JRov1nMNY25sikMRZKl/C27iMuICiJHVVKMuK4+ij32vvNpklm9XMgbAQSEpbzDaYyqGRzMFfbqdFnnQyiQaUtWnSxcc+TK9QC6DgkP0+FrkasWE27/y6ou4qrrd8gyij4PKlc5oz39eXKaedGG/nZnRZb/sCiPqBFqTQoCB9A6NPpVzq+77dIsisbmfLRqVPohARvP2CmHSCL0luv8n2Zy1syk9sio/nh8dRb6tjyKFhiA0ZLg3Unn1bi+akSATYUk1l9pF09SnkuaJuy9lhvhwJEKvRLmKoEP9tU5y7yzoQ1lFUvWzMpTjtDRoLTyDFnth+I5R+r2f4qgYg/k4gAvCAUSXfX5aCegX6frvYo3BIEjlYRuXOMG/4AL6A/0Dpcj4t0QaA9F3U/KSO73+qop0G45U5BB9zi0kKmS82aoV0FD/MCqkoFkeHdYQv4FjWbTz3omcYyohUOMwwvxuUc7xeX6GgD85Q7vCvqrts3A==
  template:
    metadata:
      name: sentry-secret
      namespace: code-place-dev
    type: Opaque
