apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:14.12

  primaryUpdateStrategy: unsupervised

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi

  storage:
    storageClass: longhorn-cnpg
    size: 30Gi

  bootstrap:
    initdb:
      database: code-place
      owner: code-place
      secret:
        name: pg-credentials
