# Generated by Django 3.2.25 on 2025-07-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='first_failed_tc_idx',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
