# Generated by Django 3.2.25 on 2025-08-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_first_failed_tc_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='judge_time',
            field=models.DateTimeField(null=True),
        ),
    ]
