# Generated by Django 3.2.25 on 2025-09-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_judge_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='judge_time',
            new_name='judge_start_time',
        ),
        migrations.AddField(
            model_name='submission',
            name='judge_end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
