# Generated by Django 5.2.15 on 2026-10-07 05:15

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # 운영 중 submission 테이블 잠금을 피하기 위해 CONCURRENTLY로 생성
    atomic = False

    dependencies = [
        ('problem', '0004_problemaihintlog_problem_ai__user_id_7fac82_idx'),
        ('submission', '0004_auto_20250904_1525'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='submission',
            index=models.Index(condition=models.Q(('contest__isnull', True), ('result', 0)), fields=['user_id', 'problem', 'create_time'], name='submission_user_accepted_idx'),
        ),
    ]
