# Generated by Django 3.2.25 on 2024-08-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='algorithm_score',
            field=models.BigIntegerField(default=0),
        ),
    ]
