# Generated by Django 3.2.9 on 2024-05-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20240506_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscore',
            old_name='high_score',
            new_name='High_score',
        ),
    ]
