# Generated by Django 3.2.25 on 2024-06-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20180501_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField()),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'link_announcement',
                'ordering': ('-create_time',),
            },
        ),
    ]
