# Generated by Django 3.2.25 on 2024-07-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_linkannouncement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkannouncement',
            options={'ordering': ('-la_id',)},
        ),
        migrations.RenameField(
            model_name='linkannouncement',
            old_name='created_by',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='linkannouncement',
            name='last_update_time',
        ),
        migrations.RemoveField(
            model_name='linkannouncement',
            name='link',
        ),
        migrations.AddField(
            model_name='linkannouncement',
            name='la_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkannouncement',
            name='new_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linkannouncement',
            name='create_time',
            field=models.TextField(),
        ),
    ]
