# Generated by Django 3.2.25 on 2024-07-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_auto_20240705_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkannouncement',
            name='id',
        ),
        migrations.AlterField(
            model_name='linkannouncement',
            name='la_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
