---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: code-place-prod
spec:
  encryptedData:
    .dockerconfigjson: AgC7aSGMNr6SaJmeda+LMAFcdDEJTmk1VfKsYxfMRxT8PI1m2hPCLrZyEoXJsBXOwJrKWC/CRdkm7g4e45wDvYVczylN6IEQhmqKQs1fdZf4slBdAvPcUI9bO9oTLT5qTbhAaEOGnmBmUry1rWA6i23ghq2PGfO4510Erb/eh9qUeGc6eAcb+Ji27XV06WWta0d/hWW4qEbfDWO6+BbX5lKqV7ssS6Qgjlp1cEfGZ8oTcL/CpKQLnqXNlc++z9WeKu1PqvifISSvJrPfHQSserqgAHlX1tKvpk1aVa7R2GcjxdFNmRq+dJYn+i5Doph9GmKa7wu7E1smBgLxjTujAdDmz6KkC89+Tx9FMJ1xGWjR03GQsBBVxd34kxExbLvcgAKLMtKwyPlNupD5GEIIYC+IBlmUwJ2ItwDVBXl0hlw7+6tpjJ52apNwWu9e491m+Biodw9RtmCLXT602l26sQ52gZJ4ikwJENqdRxH5EOEJszlnbJ+ob/zTAZVtsuAjiknY4F2a6vSOh6JyNsYyh+yTlRjEvCfGnaDIpri55ONuhqiu6nt5qdJ38JMdpPgEuys+WJXfhLuPEItc4vpc8hP7rS9bDVhWqiX+CH6YJMlK08vNhK/12LGo3QfYeFdQ75wVF1M1L3Se3yxQNcOjNnjU53mR9jtLnSem6oR93NjuLR39XJ4dD7+yt9n9EjVMulDAc/Q4FLhzG4vtH1g23pElTinUvLEggzmh4pCb7RfgFZpKwO91QvusxbHJvqlGMrUTODdyuz7RweR8ginkBjHN+8UqmGytMwdPFgyu1lbozaijSFco0toQxNKwnS4y5rXOSurpFSTbXeYVOwyHbdcBgQQ1z12TDTAAJGo7cw==
  template:
    metadata:
      name: regcred
      namespace: code-place-prod
    type: kubernetes.io/dockerconfigjson
