---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentry-secret
  namespace: code-place-prod
spec:
  encryptedData:
    SENTRY_DSN_BACKEND: AgBkOSmw2otyN8C7p+kChfEh/AUNC2Ksg3UiH1+9ThzBlJturkFLd9QFzpCIJB/fBN739OHue/nHWtqWicZ+e64aAITY9l3yhMDYAaYAmcE6pZAi5/zQK/vd8jhagiy7y+qRQ4EqueaLSB6HoKhq5/aWMgiMadsne93xLEATl/kPKCIxt/5BokpuzTB9U6ODfj6UhN2HOIV5ECz3i2U/TSAdxbvKl0/673ZUJwrEKIkR2QiK8UF7yp7vTfJjZQ3lQgIKNQqMNbzh26QcjHWmghT7voE/8HZGtAm2fOB9cjreX+D1UrjelAtbknGEpgD1cGujBY1nk8OJSsh58wNR5yO6SJeMOQwRXM2vxldDGY6InqII5RaqP+62vUBAVBDWHqZyE/57v/8dUQG7VUaOAhZXdiLapQ6FmmfeqqGFg8Uvpcmnho21BQcGGETvkUqzbgGIqn8RiN5aaNJDtks9RJ+0LalCbYP/9yfuR4ybgdy75hzkTZwOe7Up3bz6noEJMvM3Z3ZBGoo8EwpoG6FKyB3/LQzUzDQiEX9iexK0yJCgyCjIZVScZRFDaeb200rPxxIZBWLRHb6hsBapU5Jh+L8fn03Oi7KVbwhWRPNxaDrPrNZeG/VpIeiZ90nlTglgMwBw16UvL5cwsp1ORiBHGIfzJzEH5O/TATtSoiPEpVD0Gn+RhDTn7lKgz71m4xXCu0R1vpifXKuHxzvgHwS+0gqn2Ybc+MdSV0On6puunN09Qn/8fpdYSnZvcR8EWJORQw1cBlRSVV76qyI3GMMRncLVhRPDp5Nn5psP0jQdzcwm0/peJ2s507gs9we/kFfTtA==
  template:
    metadata:
      name: sentry-secret
      namespace: code-place-prod
    type: Opaque
