"""
Django settings for oj project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
import os
from copy import deepcopy
from utils.shortcuts import get_env

import celery.schedules
import sentry_sdk

production_env = get_env("OJ_ENV", "dev") == "production"
if production_env:
    from .production_settings import *
else:
    from .dev_settings import *

SENTRY_DSN = get_env(
    "SENTRY_DSN",
    "https://d3a5abd2562994de8fae7fca4988680a@o4511586463776768.ingest.us.sentry.io/4511586479308800",
)
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        send_default_pii=True,
        environment=get_env("SENTRY_ENVIRONMENT", get_env("OJ_ENV", "dev")),
    )

with open(os.path.join(DATA_DIR, "config", "secret.key"), "r") as f:
    SECRET_KEY = f.read()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Applications
VENDOR_APPS = [
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_dbconn_retry',
    'django_celery_beat',
]

LOCAL_APPS = [
    'account',
    'announcement',
    'community',
    'conf',
    'problem',
    'contest',
    'ranking',
    'banner',
    'popup',
    'profile',
    'contents',
    'school',
    'utils',
    'submission',
    'options',
    'judge',
]

INSTALLED_APPS = VENDOR_APPS + LOCAL_APPS

MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'account.middleware.APITokenAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'account.middleware.AdminRoleRequiredMiddleware',
    'account.middleware.SessionRecordMiddleware',
    # 'account.middleware.LogSqlMiddleware',
)

if production_env:
    MIDDLEWARE = MIDDLEWARE + ('django.middleware.csrf.CsrfViewMiddleware',)

ROOT_URLCONF = 'oj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'oj.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/public/'

AUTH_USER_MODEL = 'account.User'

TEST_CASE_DIR = os.path.join(DATA_DIR, "test_case")

AVATAR_URI_PREFIX = "/public/avatar"
AVATAR_UPLOAD_DIR = f"{DATA_DIR}{AVATAR_URI_PREFIX}"

UPLOAD_PREFIX = "/public/upload"
UPLOAD_DIR = f"{DATA_DIR}{UPLOAD_PREFIX}"

BANNER_URI_PREFIX = "/public/banner"
BANNER_DIR = f"{DATA_DIR}{BANNER_URI_PREFIX}"

POPUP_URI_PREFIX = "/public/popup"
POPUP_DIR = f"{DATA_DIR}{POPUP_URI_PREFIX}"

STATICFILES_DIRS = [os.path.join(DATA_DIR, "public")]

LOGGING_HANDLERS = ['console']
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] - [%(levelname)s] - [%(name)s:%(lineno)d]  - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': LOGGING_HANDLERS,
            'level': 'ERROR',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': LOGGING_HANDLERS,
            'level': 'ERROR',
            'propagate': True,
        },
        '': {
            'handlers': LOGGING_HANDLERS,
            'level': 'WARNING',
            'propagate': True,
        }
    },
}

REST_FRAMEWORK = {
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_RENDERER_CLASSES': ('rest_framework.renderers.JSONRenderer',)
}

def env_to_bool(name, default=False):
    value = get_env(name, str(default)).lower()
    return value in ("1", "true", "yes", "on")


def parse_host_port_list(value, default_port):
    hosts = []
    for item in value.split(","):
        item = item.strip()
        if not item:
            continue
        if ":" in item:
            host, port = item.rsplit(":", 1)
        else:
            host, port = item, default_port
        hosts.append((host, int(port)))
    return hosts


REDIS_USE_SENTINEL = env_to_bool("REDIS_USE_SENTINEL")
REDIS_SENTINEL_MASTER_NAME = get_env("REDIS_SENTINEL_MASTER_NAME", "mymaster")
REDIS_SENTINEL_HOSTS = parse_host_port_list(
    get_env("REDIS_SENTINEL_HOSTS", "%s:%s" % (REDIS_CONF["host"], REDIS_CONF["port"])),
    REDIS_CONF["port"])
REDIS_URL = "redis://%s:%s" % (REDIS_CONF["host"], REDIS_CONF["port"])
REDIS_SENTINEL_URLS = ";".join("sentinel://%s:%s/4" % (host, port) for host, port in REDIS_SENTINEL_HOSTS)


def redis_config():

    def make_key(key, key_prefix, version):
        return key

    config = {
        "BACKEND": "utils.cache.MyRedisCache",
        "LOCATION": f"{REDIS_URL}",
        "TIMEOUT": None,
        "KEY_PREFIX": "",
        "KEY_FUNCTION": make_key
    }
    if REDIS_USE_SENTINEL:
        config["LOCATION"] = "redis://%s/0" % REDIS_SENTINEL_MASTER_NAME
        config["OPTIONS"] = {
            "CLIENT_CLASS": "django_redis.client.SentinelClient",
            "SENTINELS": REDIS_SENTINEL_HOSTS,
            "CONNECTION_POOL_CLASS": "redis.sentinel.SentinelConnectionPool",
            "CONNECTION_FACTORY": "django_redis.pool.SentinelConnectionFactory",
        }
    return config


CACHES = {"default": redis_config()}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

IP_HEADER = "HTTP_X_REAL_IP"

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in get_env("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


if REDIS_USE_SENTINEL:
    DJANGO_REDIS_CONNECTION_FACTORY = "django_redis.pool.SentinelConnectionFactory"
    CELERY_BROKER_URL = REDIS_SENTINEL_URLS
    CELERY_RESULT_BACKEND = REDIS_SENTINEL_URLS
    CELERY_BROKER_TRANSPORT_OPTIONS = {"master_name": REDIS_SENTINEL_MASTER_NAME}
    CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {"master_name": REDIS_SENTINEL_MASTER_NAME}
else:
    CELERY_BROKER_URL = f"{REDIS_URL}/4"
    CELERY_RESULT_BACKEND = f"{REDIS_URL}/4"

CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_BEAT_SCHEDULE = {
    'calculate_user_score_basis': {
        'task': 'account.tasks.calculate_user_score_basis',
        'schedule': celery.schedules.crontab(minute=0, hour=0),    # Every day at midnight
    },
    'calculate_user_score_fluctuation': {
        'task': 'account.tasks.calculate_user_score_fluctuation',
        'schedule': celery.schedules.crontab(minute='*/1'),    # Every minute
    },
    'update_weekly_stats': {
        'task': 'problem.tasks.update_weekly_stats',
        'schedule': celery.schedules.crontab(hour=0, minute=0, day_of_week='mon'),    # Every Monday at midnight
    },
    'update_bonus_problem': {
        'task': 'problem.tasks.update_bonus_problem',
        'schedule': celery.schedules.crontab(hour=0, minute=0, day_of_week='mon'),    # Every Monday at midnight
    }
}
