# Generated by Django 3.2.9 on 2023-12-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20231205_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FREE', 'Free'), ('QUES', 'Question'), ('PROM', 'Promotion'), ('SUBJ', 'Subject'), ('REQU', 'Request'), ('UPDA', 'Update')], default='FREE', max_length=4),
        ),
    ]
