version: "3.9"

services:
  frontend:
    image: registry.code-place-dev.site/code-place-dev/frontend:latest
    ports:
      - "8001:8000"
      - "1444:1443"
    volumes:
      - /etc/letsencrypt/live/code-place-dev.site/fullchain.pem:/etc/letsencrypt/live/code-place-dev.site/fullchain.pem:ro
      - /etc/letsencrypt/live/code-place-dev.site/privkey.pem:/etc/letsencrypt/live/code-place-dev.site/privkey.pem:ro
      - data_volume:/data:ro

  backend:
    image: registry.code-place-dev.site/code-place-dev/backend:latest
    volumes:
      - data_volume:/data:rw

  celery-beat:
    image: registry.code-place-dev.site/code-place-dev/backend:latest

  celery-worker:
    image: registry.code-place-dev.site/code-place-dev/backend:latest

  oj-judge:
    image: registry.code-place-dev.site/code-place-dev/judge-server:1.0.1

  oj-postgres:
    ports:
      - "5438:5432"

volumes:
  data_volume:
    external: true
    name: backend-data-dev
