version: "3.9"

services:
  auth-server:
    image: registry.code-place-dev.site/code-place-hub/auth-server:latest
    ports:
      - "3444:80"
    env_file:
      - .env
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: on-failure
