# kubernetes/monitoring/grafana/values-ingress.yaml
# shared Grafana reverse proxy values

ingress:
  enabled: true
  hosts:
    - monitoring.code-place-dev.site
  tls:
    - hosts:
        - monitoring.code-place-dev.site
