apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    spec:
      containers:
        - name: celery-worker
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              value: "prod"
            - name: SENTRY_RELEASE
              value: "3a65dc653fc6fb3050a04e373bbf58e7d391c762-prod"
