apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  labels:
    app: celery-beat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: celery-beat
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              value: "prod"
            - name: SENTRY_RELEASE
              value: "3a65dc653fc6fb3050a04e373bbf58e7d391c762-prod"
