services:
  scheduler:
    image: juniper0917/csep-scheduler:latest
    restart: always
#    depends_on:
#      - oj-postgres
#      - backend
    volumes:
      - ../scheduler/logs:/app/logs
    env_file:
      - .env
    networks:
      - prod-network

networks:
  prod-network:
    external: true
    name: code-place-prod-network