# Generated by Django 3.2.9 on 2024-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_problem_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='weekly_accepted_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='weekly_submission_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='weekly_success_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
