# Generated by Django 3.2.9 on 2024-02-07 13:12

from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0019_auto_20240205_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='curr_week_info',
            field=models.JSONField(default=problem.models.get_default_week_info),
        ),
        migrations.AlterField(
            model_name='problem',
            name='last_week_info',
            field=models.JSONField(default=problem.models.get_default_week_info),
        ),
    ]
