# Generated by Django 3.2.9 on 2024-02-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0022_alter_problem_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='field',
            field=models.IntegerField(default=0),
        ),
    ]
