# Generated by Django 3.2.25 on 2025-08-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='community_type',
        ),
    ]
