# Generated by Django 3.2.25 on 2025-09-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_post_community_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='question_status',
            field=models.CharField(blank=True, choices=[('OPEN', '진행중'), ('CLOSED', '해결됨')], max_length=20, null=True),
        ),
    ]
