# Generated by Django 3.2.9 on 2024-11-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_image', models.TextField()),
                ('link_url', models.URLField()),
                ('visible', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'popup',
                'ordering': ('order', '-create_time'),
            },
        ),
    ]
