# Generated by Django 3.2.25 on 2024-11-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popup_image_width',
            field=models.IntegerField(null=True),
        ),
    ]
