# Generated by Django 3.2.9 on 2024-12-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0002_popup_popup_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='link_url',
            field=models.TextField(),
        ),
    ]
