# Generated by Django 3.2.25 on 2026-04-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problemaihintlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemaihintlog',
            options={},
        ),
        migrations.AddIndex(
            model_name='problemaihintlog',
            index=models.Index(fields=['user', 'created_at'], name='problem_ai__user_id_a502c8_idx'),
        ),
        migrations.AddIndex(
            model_name='problemaihintlog',
            index=models.Index(fields=['problem', 'created_at'], name='problem_ai__problem_3abff5_idx'),
        ),
    ]
