# Generated by Django 3.2.25 on 2026-04-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20260421_1122'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='problemaihintlog',
            index=models.Index(fields=['user', 'problem', 'created_at'], name='problem_ai__user_id_7fac82_idx'),
        ),
    ]
