# Generated by Django 3.2.9 on 2024-02-03 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0017_auto_20240203_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='weekly_solvers',
            field=models.ManyToManyField(blank=True, related_name='solvers', to=settings.AUTH_USER_MODEL),
        ),
    ]
