# Generated by Django 3.2.9 on 2024-02-05 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0018_problem_weekly_solvers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='weekly_accepted_number',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='weekly_solvers',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='weekly_submission_number',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='weekly_success_rate',
        ),
        migrations.AddField(
            model_name='problem',
            name='curr_week_info',
            field=models.JSONField(default={'accepted': 0, 'submission': 0, 'success_rate': 0.0}),
        ),
        migrations.AddField(
            model_name='problem',
            name='curr_week_solver',
            field=models.ManyToManyField(blank=True, related_name='curr_week_solver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_most_difficult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='last_week_info',
            field=models.JSONField(default={'accepted': 0, 'submission': 0, 'success_rate': 0.0}),
        ),
        migrations.AddField(
            model_name='problem',
            name='last_week_solver',
            field=models.ManyToManyField(blank=True, related_name='last_week_solver', to=settings.AUTH_USER_MODEL),
        ),
    ]
