# Generated by Django 3.2.9 on 2024-02-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0021_auto_20240207_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='field',
            field=models.TextField(default='Math'),
        ),
    ]
