location /public {
    root /data;
}

location /api/problem/llm_hint {
    include api_proxy.conf;
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    gzip off;
}

location /api {
    include api_proxy.conf;
}

location /admin {
    root /usr/share/nginx/html;
    try_files $uri $uri/ admin/index.html =404;
}

location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html =404;
}
